# Generated by Django 6.0.6 on 2026-06-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_supplier_phone_alter_warehouse_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='notes',
            new_name='note',
        ),
    ]
